one more

diff --git a/.github/workflows/yay.yml b/.github/workflows/yay.yml
--- a/.github/workflows/yay.yml
+++ b/.github/workflows/yay.yml
@@ -22,6 +22,11 @@ jobs:
     steps:
       - run: "exit 0"
 
+  four:
+    runs-on: ubuntu-20.04
+    steps:
+      - run: "exit 1"
+
   approach-a-success:
     # We should never skip this job
     needs: [one, two]
@@ -41,7 +46,7 @@ jobs:
     # We should never skip this job
     needs: [one, two, three]
     # The name has to match the name from the next job
-    name: Approach A with one skip
+    name: Approach A - one skipped
     runs-on: ubuntu-20.04
     # This is necessary since a failed/skipped job would cause this job to be skipped
     if: always()
@@ -49,4 +54,19 @@ jobs:
       - name: Check for any failures
         # This sadly requires duplication of the list declated in needs
         if: needs.one.result == 'failure' || needs.two.result == 'failure' || needs.three.result == 'failure'
+        run: "exit 2"
+
+  # This one includes a job that is skipped
+  approach-a-failure:
+    # We should never skip this job
+    needs: [one, two, three, four]
+    # The name has to match the name from the next job
+    name: Approach A - one failing
+    runs-on: ubuntu-20.04
+    # This is necessary since a failed/skipped job would cause this job to be skipped
+    if: always()
+    steps:
+      - name: Check for any failures
+        # This sadly requires duplication of the list declated in needs
+        if: needs.one.result == 'failure' || needs.two.result == 'failure' || needs.three.result == 'failure' || needs.four.result == 'failure'
         run: "exit 2"
